# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strongbox < Formula
  desc "Encryption for git users"
  homepage "https://github.com/uw-labs/strongbox"
  version "2.0.0"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/uw-labs/strongbox/releases/download/v2.0.0/strongbox_2.0.0_darwin_amd64"
      sha256 "20de867538f6597ce5d1d32dec167d641543eaf8295b7f7594b68c6513470535"

      def install
        bin.install "strongbox_2.0.0_darwin_amd64" => "strongbox"
      end
    end
    on_arm do
      url "https://github.com/uw-labs/strongbox/releases/download/v2.0.0/strongbox_2.0.0_darwin_arm64"
      sha256 "b75d06bc8563a29af0c21c2fc2d22f1d97bca9712e1407013a8dedad41de7c18"

      def install
        bin.install "strongbox_2.0.0_darwin_arm64" => "strongbox"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uw-labs/strongbox/releases/download/v2.0.0/strongbox_2.0.0_linux_amd64"
        sha256 "e0336f503d873082a03f6f87a28c74d28922faff9a42319864d7e79813f242e2"

        def install
          bin.install "strongbox_2.0.0_linux_amd64" => "strongbox"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/uw-labs/strongbox/releases/download/v2.0.0/strongbox_2.0.0_linux_armv6"
        sha256 "3fd93f95ee3381f0076408e1f129002a7f196a2dbd96b4a94f0c4b91c97bb61f"

        def install
          bin.install "strongbox_2.0.0_linux_armv6" => "strongbox"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uw-labs/strongbox/releases/download/v2.0.0/strongbox_2.0.0_linux_arm64"
        sha256 "5599253c05bd1cd18eac72f360469744df93444f3ea86f4fa44b6165584d0fef"

        def install
          bin.install "strongbox_2.0.0_linux_arm64" => "strongbox"
        end
      end
    end
  end
end
