# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strongbox < Formula
  desc "Encryption for git users"
  homepage "https://github.com/uw-labs/strongbox"
  version "2.0.0-RC4"
  license "LGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/uw-labs/strongbox/releases/download/v2.0.0-RC4/strongbox_2.0.0-RC4_darwin_amd64"
      sha256 "b791b03996a18e0d4f470347f054a65775cc3f28eb05ded5ece8f745f6ecd594"

      def install
        bin.install "strongbox_2.0.0-RC4_darwin_amd64" => "strongbox"
      end
    end
    on_arm do
      url "https://github.com/uw-labs/strongbox/releases/download/v2.0.0-RC4/strongbox_2.0.0-RC4_darwin_arm64"
      sha256 "a587d0d411761d791378fe0193b5b1cb87e67c3b4dbc4c6c3eb8aa4518feaf94"

      def install
        bin.install "strongbox_2.0.0-RC4_darwin_arm64" => "strongbox"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uw-labs/strongbox/releases/download/v2.0.0-RC4/strongbox_2.0.0-RC4_linux_amd64"
        sha256 "fe6efdb40de528d83cefcbe25b4f6340988143b207b9bf9c410e05547671ac35"

        def install
          bin.install "strongbox_2.0.0-RC4_linux_amd64" => "strongbox"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/uw-labs/strongbox/releases/download/v2.0.0-RC4/strongbox_2.0.0-RC4_linux_armv6"
        sha256 "f8cbac20a62f7b61934164b5e82e51f802f0caa5a5c62c5112024d396942f1f9"

        def install
          bin.install "strongbox_2.0.0-RC4_linux_armv6" => "strongbox"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/uw-labs/strongbox/releases/download/v2.0.0-RC4/strongbox_2.0.0-RC4_linux_arm64"
        sha256 "be84e36035d14a5f1d438508fb4782df4f2c037e31d1ab9f215e3f8b407de8a7"

        def install
          bin.install "strongbox_2.0.0-RC4_linux_arm64" => "strongbox"
        end
      end
    end
  end
end
